"""Ray-traces a spinning Bitcoin coin into 1-bit SSD1306 frames for btc/coin_frames.h (+ a preview PNG)."""
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent.parent
FRAMES = 36  # 10 degrees per frame
W, HGT = 56, 64  # frame size in pixels: the left part of the 128x64 screen
SS = 4  # supersampling per axis
R = 25.0  # coin radius in pixels
H = 3.0  # half thickness
LIGHT = np.array([-0.35, -0.45, 0.82])
LIGHT /= np.linalg.norm(LIGHT)
BAYER = np.array([[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]]) / 16 + 1 / 32


def face_ink():
    """Mask of dark 'engraving' on the coin face: an inner ring and the ₿ symbol. 1 = ink."""
    n = 512
    img = Image.new("L", (n, n), 0)
    d = ImageDraw.Draw(img)
    c = n / 2
    r = 0.86 * c
    d.ellipse([c - r, c - r, c + r, c + r], outline=255, width=int(0.035 * n))
    font = ImageFont.truetype("/usr/share/fonts/liberation/LiberationSans-Bold.ttf", int(n * 0.62))
    box = d.textbbox((0, 0), "B", font=font)
    bw, bh = box[2] - box[0], box[3] - box[1]
    x0, y0 = c - bw / 2 - box[0] + n * 0.02, c - bh / 2 - box[1]
    d.text((x0, y0), "B", font=font, fill=255)
    # The two strokes through the top and bottom that turn B into ₿.
    sw = n * 0.06
    for sx in (c - bw * 0.14, c + bw * 0.14):
        d.rectangle([sx - sw / 2, c - bh / 2 - n * 0.09, sx + sw / 2, c - bh / 2 + 2], fill=255)
        d.rectangle([sx - sw / 2, c + bh / 2 - 2, sx + sw / 2, c + bh / 2 + n * 0.09], fill=255)
    return np.asarray(img) > 127


def render(theta, ink):
    """Returns a HGT x W float image (0..1 brightness) of the coin rotated by theta about the vertical axis."""
    ys, xs = np.mgrid[0 : HGT * SS, 0 : W * SS]
    x = (xs + 0.5) / SS - W / 2
    y = (ys + 0.5) / SS - HGT / 2
    c, s = np.cos(theta), np.sin(theta)
    # Ray from the viewer along -z, expressed in coin space (coin rotated by theta about y).
    ox, oz = c * x, s * x  # origin at z=0 world
    dx, dz = s, -c  # direction (0,0,-1) rotated by -theta
    oy = y
    t_best = np.full(x.shape, np.inf)
    kind = np.zeros(x.shape, np.int8)  # 0 none, 1 front, 2 back, 3 side

    for zf, kd in ((H, 1), (-H, 2)):
        with np.errstate(divide="ignore", invalid="ignore"):
            t = (zf - oz) / dz
        px, py = ox + t * dx, oy
        hit = (px**2 + py**2 <= R**2) & np.isfinite(t) & (t < t_best)
        t_best[hit], kind[hit] = t[hit], kd

    # Side: (ox + t dx)^2 + oy^2 = R^2, |oz + t dz| <= H.
    a = dx**2
    if a > 1e-9:
        disc = R**2 - oy**2
        ok = disc >= 0
        root = np.sqrt(np.where(ok, disc, 0))
        for sign in (-1, 1):
            t = (sign * root - ox) / dx
            pz = oz + t * dz
            hit = ok & (np.abs(pz) <= H) & (t < t_best)
            t_best[hit], kind[hit] = t[hit], 3

    px = ox + np.where(np.isfinite(t_best), t_best, 0) * dx
    py = oy
    world = lambda nx, nz: (c * nx + s * nz, -s * nx + c * nz)  # coin-space normal to world

    out = np.zeros(x.shape)
    for kd, nz in ((1, 1.0), (2, -1.0)):
        m = kind == kd
        wx, wz = world(0.0, nz)
        lam = max(0.0, wx * LIGHT[0] + wz * LIGHT[2])
        half = LIGHT + np.array([0, 0, 1.0])
        half /= np.linalg.norm(half)
        spec = max(0.0, wx * half[0] + wz * half[2]) ** 40
        u = px[m] * (1 if kd == 1 else -1)  # back face mirrored so the symbol reads correctly
        iu = np.clip(((u / R + 1) / 2 * ink.shape[1]).astype(int), 0, ink.shape[1] - 1)
        iv = np.clip(((py[m] / R + 1) / 2 * ink.shape[0]).astype(int), 0, ink.shape[0] - 1)
        base = 0.45 + 0.6 * lam + 0.6 * spec
        out[m] = np.where(ink[iv, iu], 0.0, base)

    m = kind == 3
    ang = np.arctan2(py[m], px[m])
    nx, ny = np.cos(ang), np.sin(ang)
    wx, wz = world(nx, 0.0)
    lam = np.maximum(0, wx * LIGHT[0] + ny * LIGHT[1] + wz * LIGHT[2])
    ridges = (np.sin(ang * 70) > 0) * 0.35 + 0.65  # milled edge
    out[m] = (0.35 + 0.8 * lam) * ridges

    return out.reshape(HGT, SS, W, SS).mean(axis=(1, 3))


def dither(img):
    th = np.tile(BAYER, (HGT // 4, W // 4))
    return img > th


def to_pages(bits):
    """SSD1306 page format: for each 8-row page, one byte per column, bit k = row page*8+k."""
    out = bytearray()
    for p in range(HGT // 8):
        for col in range(W):
            b = 0
            for k in range(8):
                if bits[p * 8 + k, col]:
                    b |= 1 << k
            out.append(b)
    return out


def main():
    ink = face_ink()
    frames = [dither(render(2 * np.pi * i / FRAMES, ink)) for i in range(FRAMES)]

    lines = [
        "// Generated by btc/gen_coin.py. Do not edit.",
        f"const uint8_t COIN_FRAMES = {FRAMES};",
        f"const uint8_t COIN_W = {W};  // each frame: {HGT // 8} pages x COIN_W bytes, SSD1306 page format",
        f"const uint8_t COIN_DATA[{FRAMES}][{W * HGT // 8}] PROGMEM = {{",
    ]
    for f in frames:
        data = to_pages(f)
        lines.append("  {" + ",".join(f"0x{b:02x}" for b in data) + "},")
    lines.append("};")
    (HERE / "btc/coin_frames.h").write_text("\n".join(lines) + "\n")

    cols = 9
    sheet = Image.new("L", (cols * (W + 4), (FRAMES // cols) * (HGT + 4)), 40)
    for i, f in enumerate(frames):
        sheet.paste(Image.fromarray((f * 255).astype(np.uint8)), ((i % cols) * (W + 4) + 2, (i // cols) * (HGT + 4) + 2))
    (HERE / "build").mkdir(exist_ok=True)
    sheet.resize((sheet.width * 2, sheet.height * 2), Image.NEAREST).save(HERE / "build/coin_preview.png")


main()
